### ISSUE TITLE
Persistence API - Separation of Events and Snapshots

### ISSUE THREAD

**Issue by tomliversidge** [AsynkronIT/protoactor-dotnet#186]
As discussed in https://github.com/AsynkronIT/protoactor-dotnet/issues/137 and https://github.com/AsynkronIT/protoactor-dotnet/pull/136 there is an idea to separate out the concept of events vs snapshots, at different levels: 

1. At the provider level, i.e. break out IProviderState into IEventState and ISnapshotState. This would allow different stores to be used for each if desired.
2. At the actor level, i.e. explicitly opt-in to either Events, Snapshotting or both. This is a bigger change due to the coupling of the index shared between Events and Snapshots.

**Comment by rogeralsing** [comment]
Can we close this? this has been fixed, right?

**Comment by tomliversidge** [comment]
Hmmm.. 2. was done, but we still have a single interface for persistence - IProviderState, and we can still only have a single store for both snapshots and events. Having a single interface also makes it messier to decorate if someone wanted to. Don't think there is a particular demand to split it out yet though so we could always close it and re-open later if needed?

**Comment by raskolnikoov** [comment]
I also think we can close this for now and open a new tricket if users really want it separated. 👍
